version: 0.0
os: linux
files:
   - source: /bbycaSREApp
     destination: /var/bbycasre/staging
permissions:
   - object: /var/bbycasre/staging
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: bbycaSREApp/scripts/before.sh
      runas: root
    - location: bbycaSREApp/scripts/StopServer.sh
      runas: root
   AfterInstall:
    - location: bbycaSREApp/scripts/StartServer.sh
      runas: root
    - location: bbycaSREApp/scripts/after.sh
      runas: root
